spring:
  # 模板引擎
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5

  # 使用 H2 控制台
  h2.console.enabled: true

  # 数据源
  datasource:
    url: jdbc:mysql://localhost/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # elasticsearch
  data:
    elasticsearch:
      # 服务器地址
      cluster-nodes: localhost:9300

      properties:
        transport:
          tcp:
            # 连接超时时间
            # connect_timeout: 500s